[package]
edition = "2021"
name    = "affine_media_capture"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
harness = false
name    = "mix_audio_samples"

[dependencies]
napi        = { workspace = true, features = ["napi4"] }
napi-derive = { workspace = true, features = ["type-def"] }
rubato      = { workspace = true }
symphonia   = { workspace = true, features = ["all", "opt-simd"] }
thiserror   = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
block2           = { workspace = true }
core-foundation  = { workspace = true, features = ["with-uuid"] }
coreaudio-rs     = { workspace = true }
dispatch2        = { workspace = true }
libc             = { workspace = true }
objc2            = { workspace = true }
objc2-foundation = { workspace = true }
screencapturekit = { workspace = true }
uuid             = { workspace = true, features = ["v4"] }

[target.'cfg(target_os = "windows")'.dependencies]
cpal              = { workspace = true }
crossbeam-channel = { workspace = true }
windows           = { workspace = true }
windows-core      = { workspace = true }

[dev-dependencies]
criterion2 = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
